Exercice 7
Quantmetry/how-to-opensource pull request #3
Opened 2021-05-27 15:42 UTC by dhervault

2021-05-27 15:46 UTC, gmartinonQM requested changes

2021-05-27 15:46 UTC, gmartinonQM commented on README.rst
> +La documentation a été généré dans le repertoire **doc/_build**, vous pouvez la consulter dans votre navigateur web, elle est belle, mais vide. En plus de la rédaction que vous ne manquerez pas d'ajo
typo: enfin

2021-05-27 15:46 UTC, gmartinonQM commented on README.rst
> +Pour diffuser cette documentation est nécessaire de la publier sur un site publique, par exemple en utilisant ReadTheDocs_. Commencez par créer un compte en utilisant votre login GitHUB.
typo: il est nécessaire

2021-05-27 15:46 UTC, gmartinonQM commented on README.rst
> +Une fois inscrit et connecté, importez votre projet GitHUB, après avoir soigneusement choisit la branche et la version, lancez la compilation.
typo: choisi

2021-05-28 07:30 UTC, dhervault commented on README.rst
> +La documentation a été généré dans le repertoire **doc/_build**, vous pouvez la consulter dans votre navigateur web, elle est belle, mais vide. En plus de la rédaction que vous ne manquerez pas d'ajo
done

2021-05-28 07:30 UTC, dhervault commented on README.rst
> +Pour diffuser cette documentation est nécessaire de la publier sur un site publique, par exemple en utilisant ReadTheDocs_. Commencez par créer un compte en utilisant votre login GitHUB.
Done

2021-05-28 07:31 UTC, dhervault commented on README.rst
> +Une fois inscrit et connecté, importez votre projet GitHUB, après avoir soigneusement choisit la branche et la version, lancez la compilation.
Done

2021-05-28 08:52 UTC, vtaquet commented on doc/Makefile
> +	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
La commande `html` n'apparait pas sur cette version du Makefile, c'est normal ? J'imagine qu'un Makefile complet va être généré automatiquement avec `sphinx-quickstart`.

2021-05-28 08:54 UTC, vtaquet commented on README.rst
> +.. _SphynxGallery: https://sphinx-gallery.github.io/stable/getting_started.html
Typo à SphYnxGallery

2021-05-28 08:58 UTC, dhervault commented on doc/Makefile
> +	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
c'est le makefile qui a été généré et la commande 'make hmlt' fonctionne bien.
le param 'html' est géré par la commande 'sphynx-build' dont la doc est ci-dessous

```
(how_to_opensource) dhervaut@MacBook-Pro-Damien-Hervault doc % sphinx-build --help
usage: sphinx-build [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]

Création de la documentation à partir des fichiers sources. sphinx-build crée la documentation à partir des
fichiers dans SOURCEDIR et la met dans OUTPUTDIR. Il prend en compte « conf.py » de SOURCEDIR pour les valeurs de
configuration. L'outil « sphinx-quickstart » peut être utilisé pour créer des fichiers de gabarits (template),
y-compris « conf.py » . sphinx-build peut créer la documentation sous différents formats. Un format est sélectionné
par la spécification du nom du constructeur (builder) sur la ligne de commande ; par défault, HTML (constructeur «
html »). Les constructeurs peuvent s'acquitter d'autres tâches relatives à la production de la documentation. Par
défaut, tout ce qui n’est pas à jour est construit. On peut restreindre le processus à certains fichiers
spécifiques en précisant leurs noms.
```

2021-05-28 09:00 UTC, dhervault commented on README.rst
> +.. _SphynxGallery: https://sphinx-gallery.github.io/stable/getting_started.html
Done

2021-05-28 11:23 UTC, merged